<a href="https://colab.research.google.com/github/Sinrez/pyCoursera/blob/master/Numpy_HW1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Внимание! Необходимо использовать функции numpy по-максимуму! И практически никаких циклов! Это практика, просто пытаемся сделать все, что можем.=)


In [ ]:
import numpy as np
import random
import scipy.stats as spst

### 1. Отсортируйте все столбцы по нулевому столбцу:

In [ ]:
np.random.seed(21)
a = np.random.randint(0, 10, (5, 3))
print(a)

[[9 8 4]
 [0 0 8]
 [3 2 1]
 [8 9 6]
 [0 4 6]]


In [ ]:
# Дописать код здесь
np.sort(a)

array([[4, 8, 9],
       [0, 0, 8],
       [1, 2, 3],
       [6, 8, 9],
       [0, 4, 6]])

In [ ]:
np.sort(a, axis= 0) 

array([[0, 0, 1],
       [0, 2, 4],
       [3, 4, 6],
       [8, 8, 6],
       [9, 9, 8]])

### 2. Найти наиболее частое значение в массиве

In [ ]:
# Дописать код здесь
lt = np.random.randint(10, 20, size = 10)
lt

array([14, 19, 10, 19, 14, 19, 10, 11, 13, 18])

In [ ]:
np.argmax(np.bincount(lt))

19

### 3. Даны наборы точек x (`X`) и y (`Y`). Каждый набор описывает прямую i (X[i], Y[i]). Найти расстояние от точки `р` до каждой прямой.

In [ ]:
def distance(P0, P1, p):
    # Дописать код здесь
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0] - p[...,0]) * T[:,0] + (P0[:,1] - p[...,1]) * T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U * T - p
    return np.sqrt((D**2).sum(axis=1))
    

In [ ]:
P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[3.17492359 5.34157116 4.3954823  4.44992119 1.36240759 9.62023067
 4.33456319 7.98682002 0.30570239 6.34123228]


### 4. Найти n наибольших значений в массиве

In [ ]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
Z.max()

9999

In [ ]:
# Дописать код здесь
def n_max(a,n):
  return a[a.argsort()[-n:]]

n_max(Z,n)

array([9995, 9996, 9997, 9998, 9999])

### 5. Дан двумерный массив. Найти все различные строки

In [ ]:
Z = np.random.randint(0, 2, (6,3))
print(Z)

[[0 0 1]
 [1 0 0]
 [0 0 1]
 [1 0 0]
 [1 0 0]
 [0 1 0]]


In [ ]:
# Дописать код здесь
# unique_rows = 
np.unique(Z, axis=0)

array([[0, 0, 1],
       [0, 1, 0],
       [1, 0, 0]])

### 6. Разбить массив на убывающие подмассивы.  
Подсказка: np.diff()  
Используйте библиотеку `numpy`, не используйте циклы.

In [ ]:
# Дописать код здесь
import numpy as np
Z = np.arange(1000)
np.random.shuffle(Z)
a = np.diff(Z)
c = np.where(a < 0)
np.split(Z, c[0])

[array([], dtype=int64),
 array([942]),
 array([675,  33]),
 array([765, 113]),
 array([478, 125]),
 array([548, 271]),
 array([929, 416]),
 array([855, 106, 549]),
 array([772, 241, 613]),
 array([783, 318, 640]),
 array([947]),
 array([606]),
 array([366,  40, 108]),
 array([798]),
 array([378, 324]),
 array([981]),
 array([866,  88]),
 array([845]),
 array([730,  32, 301]),
 array([723]),
 array([591, 332, 434]),
 array([917, 746]),
 array([826, 351, 904]),
 array([993, 540]),
 array([906,   7]),
 array([990,  52]),
 array([553]),
 array([515, 385]),
 array([956, 682]),
 array([923]),
 array([558, 225]),
 array([865, 261, 882]),
 array([893,  63]),
 array([751, 359]),
 array([894]),
 array([390]),
 array([337,  77, 624, 707]),
 array([972]),
 array([186,  57, 107, 174]),
 array([985, 381]),
 array([410, 206, 660]),
 array([844, 242]),
 array([969]),
 array([215, 100]),
 array([547]),
 array([421, 295, 637]),
 array([857, 618]),
 array([699, 569]),
 array([818, 380]),
 array([978]),


### 7. Дан массив arr, необходимо найти среднее значение внутри групп, группа определена массивом g. 
Например, для  
`arr = [4, 2, 1, 5, 2, 5, 1, 3]` и   
`g =   [0, 1, 1, 0, 1, 0, 1, 0]` (4 относится к группе 0, 2 к группе 1 и т. д.)   
Средние по группам: `[4.25, 1.5]`  
Подсказка: `np.bincount()`   
Используйте библиотеку `numpy`, не используйте циклы.

In [ ]:
# Дописать код здесь
# непонятно как решать, в сети не нашел понятных примеров

### 8. Перемножить две квадратные матрицы двумя способами -- без использования пакета numpy и с ним. Сравнить время вычислений



In [ ]:
# Дописать код здесь
np.random.seed(21)
a = np.random.randint(0, 10, (3, 3))
b = np.random.randint(0, 10, (3, 3))
print(a)
print('-' * 6)
print(b)

[[9 8 4]
 [0 0 8]
 [3 2 1]]
------
[[8 9 6]
 [0 4 6]
 [4 4 7]]


In [ ]:
# без np
def matrixmult (A, B):
    C = [[0 for row in range(len(A))] for col in range(len(B[0]))]
    for i in range(len(A)):
        for j in range(len(B[0])):
            for k in range(len(B)):
                C[i][j] += A[i][k]*B[k][j]
    return C

print(*matrixmult (a, b))

[88, 129, 130] [32, 32, 56] [28, 39, 37]


In [ ]:
%timeit matrixmult (a, b)

10000 loops, best of 5: 37.9 µs per loop


In [ ]:
# с np
np.matmul(a, b)

array([[ 88, 129, 130],
       [ 32,  32,  56],
       [ 28,  39,  37]])

In [ ]:
%timeit np.matmul(a, b)

The slowest run took 71.78 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 5: 1.26 µs per loop


### 9. Написать функцию, которая по данной последовательности $\{A_i\}_{i=1}^n$ строит последовательность $S_n$, где $S_k = \frac{A_1 + ... + A_k}{k}$.  
Аналогично -- с помощью библиотеки **NumPy** и без нее. Сравните скорость.

In [ ]:
# Дописать код здесь
import random
lst_a_np = np.random.rand(100)

def seq_a(A):
    S = np.cumsum(A)/(np.arange(A.shape[0])+1) 
    return S

print(seq_a(lst_a_np))

[0.99836916 0.95266175 0.71172888 0.74290655 0.72772514 0.76102491
 0.69756471 0.6664818  0.63662104 0.64421187 0.59968561 0.59431494
 0.62378052 0.59166022 0.56394979 0.57868368 0.57693167 0.58426863
 0.5951988  0.5828909  0.57460519 0.57527598 0.57850965 0.56943829
 0.56681898 0.55744571 0.54431103 0.53821585 0.55269255 0.5415581
 0.53656993 0.5203656  0.53437766 0.52053836 0.51603879 0.50496012
 0.4965276  0.50524275 0.5069306  0.49849983 0.51069629 0.50721232
 0.51640753 0.50945493 0.5139372  0.51596087 0.50999434 0.50438879
 0.51201318 0.51841825 0.51390382 0.5168556  0.52109014 0.52786195
 0.52158534 0.52918548 0.52064021 0.51240832 0.51585461 0.52103068
 0.52817581 0.52331719 0.5193216  0.51390427 0.51028875 0.51698293
 0.5136381  0.51303138 0.50907323 0.50707482 0.51137616 0.51223069
 0.51267024 0.5179836  0.51849146 0.5214648  0.52320015 0.52867977
 0.52355025 0.51964593 0.51929487 0.51445017 0.51869459 0.52359174
 0.52509934 0.52787826 0.53065614 0.53504924 0.5340913  0.53313

In [ ]:
# функция без NumPy
def nonnp_seq_a(A):
    S = [0 for i in range(len(A))]
    for i in range(len(A)):
        S[i] = sum(A[:i+1]) / (i+1)

    return S


print(nonnp_seq_a(lst_a_np))

[0.9983691559607862, 0.9526617528089363, 0.7117288774635516, 0.7429065469211665, 0.7277251385791658, 0.7610249148455076, 0.6975647148452636, 0.6664817977105326, 0.6366210426395514, 0.6442118735897667, 0.5996856075063891, 0.594314942101927, 0.623780520017022, 0.5916602235520979, 0.5639497930604135, 0.5786836768191814, 0.576931668954568, 0.5842686326929704, 0.5951987972264392, 0.582890898899133, 0.5746051942485146, 0.5752759778167983, 0.5785096458162288, 0.5694382884854182, 0.5668189822921644, 0.5574457117756207, 0.544311032521463, 0.5382158500652804, 0.5526925480822856, 0.5415581006875254, 0.5365699326216912, 0.5203656029646793, 0.5343776578266209, 0.5205383607292973, 0.5160387948826051, 0.5049601202466346, 0.49652759937960805, 0.5052427494456732, 0.5069306034266085, 0.4984998250802489, 0.5106962931681321, 0.5072123234782057, 0.5164075262952549, 0.5094549295475312, 0.5139371985789819, 0.515960873824118, 0.5099943370030614, 0.5043887854644505, 0.5120131764391821, 0.5184182493614928, 0.51

In [ ]:
%timeit seq_a(lst_a_np)
%timeit nonnp_seq_a(lst_a_np)

The slowest run took 133.92 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 5: 7.84 µs per loop
1000 loops, best of 5: 1.03 ms per loop


### 10. Пусть задан некоторый массив  𝑋 . Заменить все элементы с нечетными индексами на число  𝑎  (если оно не указано, то на 1), четные - возвести в куб и записать в обратном порядке на те же позиции. Массив  𝑋  при этом должен остаться без изменений. В конце требуется слить массив X с преобразованным X.

Пример:
X = [100, 200, 300, 400, 500] -> [100, a, 300, a, 500] -> [500^3, a, 300^3, a, 100^3] -> склеиваем -> [100, 200, 300, 400, 500, 500^3, a, 300^3, a, 100^3]

In [ ]:
# Дописать код здесь
def trans(X, a=1):
  
    Y = np.zeros(X.shape[0])
    Y[1::2] = a
    Y[::2] = np.flip(X[::2]) ** 3

    return Y

X = np.array([100, 200, 300, 400, 500])

trans(X)

array([1.25e+08, 1.00e+00, 2.70e+07, 1.00e+00, 1.00e+06])

### 11. Вам подаются на вход два вектора `a` и `b` в трехмерном пространстве.Заполните их случайными числами. Реализуйте их скалярное произведение с помощью  `NumPy` и без. Засеките время работы, как это показано в заданиях выше.

In [ ]:
# Дописать код здесь
c = 3
a = spst.uniform.rvs(size=c) 
b = spst.uniform.rvs(size=c)
a

array([0.34805809, 0.18220709, 0.47916503])

In [ ]:
b

In [ ]:
%timeit spst.uniform.rvs(size=c) 

The slowest run took 18.66 times longer than the fastest. This could mean that an intermediate result is being cached.
10000 loops, best of 5: 71.3 µs per loop


In [ ]:
def numpy_scalar_product(a,b):
    
    #тут ваш код
    
    if a.shape[0] == b.shape[0]:
        
        c = np.dot(a, b)
        
    else:
        
        c = 0
    
    return c

numpy_scalar_product(a,b)

0.723223248379628

In [ ]:
%timeit numpy_scalar_product(a,b)

The slowest run took 25.69 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 5: 1.51 µs per loop


In [ ]:
def simple_scalar_product(a,b):

    if a.shape[0] == b.shape[0]:
        
        c = []
        
        for i in range(a.shape[0]):
            
            c.append(a[i]*b[i])
            
        c = sum(c)
        
    else:
        
        c = 0
    
    return c

simple_scalar_product(a,b)

0.7232232483796279

In [ ]:
%timeit simple_scalar_product(a,b)

The slowest run took 12.59 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 5: 2.7 µs per loop


### 12. Написать решето Эратосфена с Numpy. Минимум циклов!

In [ ]:
# Дописать код здесь
def ersf(n):
    m = int(np.sqrt(n))
    is_prime = np.ones(n, dtype=bool)
    is_prime[:2] = False  # 0 and 1 are not primes

    for i in range(2, m):
        if is_prime[i] == False:
            continue
        is_prime[i*i::i] = False

    return np.nonzero(is_prime)[0]

n = 100

ersf(100)


array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59,
       61, 67, 71, 73, 79, 83, 89, 97])

###  13. Реализовать кодирование длин серий (Run-length encoding). Дан вектор x. Необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить.
Пример: x = np.array([2, 2, 2, 3, 3, 3, 5]). Ответ: (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [ ]:
# Дописать код здесь
import numpy as np

def encode(a):
    elements=[]
    counts=[]
    count=1
    for i in range(len(a)):
        if(i==len(a)-1):
            elements.append(a[i])
            counts.append(count)
            break
            
        
        if(a[i]==a[i+1]):
            count+=1
        else:
                elements.append(a[i])
                counts.append(count)
                count=1
    x=np.array(elements)
    s=np.array(counts)

    result = (x,s)
    return result

x = np.array([2, 2, 2, 3, 3, 3, 5])
encode(x)


(array([2, 3, 5]), array([3, 3, 1]))

### 14. Найти максимальный элемент в векторе x среди элементов, перед которыми стоит нулевой. 
Для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5

In [ ]:
# Дописать код здесь
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
zero = x==0
x[1:][zero[:-1]].max()

5

### 15. Перетасовать колоду карт, вычислить вероятность выпадения: красной карты; туза; черного валета или шестерки (все - в Python). Подкрепить это экспериментами, сделать выводы

In [ ]:

def take_card():
  """
  вытаскивание произвольной карты
  """
  suits = np.array(["Черви", "Бубны", "Пики", "Трефы"])
  faces = np.array(["2", "3", "4", "5", "6", "7", "8", "9", "10", "J", "Q", "K", "A"])
  np.random.shuffle(faces)
  np.random.shuffle(suits)
  deck = []
  for f,s in zip(faces,suits):
    deck.append((s,f))
  return deck[0]



def card_prob():
  cards_count = 36
  # cards = np.arange(36)+1
  red_cards = 26
  print(f'Вероятность вытащить красную карту: {"{:.0%}".format(red_cards /cards_count)}')
  suit, face = take_card()
  print(f'Вытащили карту масти {suit}, номиналом {face}')
  print(f'Вероятность черного валета или черной шестерки: {"{:.0%}".format(1 /cards_count)}')

card_prob()

Вероятность вытащить красную карту: 72%
Вытащили карту масти Пики, номиналом 5
Вероятность черного валета или черной шестерки: 3%


### 16. Дана матрица X и два вектора одинаковой длины i и j. Построить вектор np.array([X[i[0], j[0]], X[i[1], j[1]], . . . , X[i[N-1], j[N-1]]]).

In [ ]:
# Дописать код здесь
from random import randint
i = [randint(0,9) for indx in range(10)]
j = [randint(0,9) for indx in range(10)]
x = [[randint(0,9) for indx in range(10)] for jndx in range(10)]
print(i)
print(j)
print('-' * 80)
print(x)
print('=' * 80)

np = []
for indx in range(10):
    np.append(x[i[indx]][j[indx]])
print(np)

[0, 6, 6, 5, 4, 2, 7, 2, 3, 4]
[4, 9, 5, 1, 9, 3, 6, 3, 5, 6]
--------------------------------------------------------------------------------
[[7, 0, 6, 7, 4, 5, 5, 3, 9, 4], [9, 9, 5, 8, 9, 2, 4, 8, 3, 6], [3, 2, 2, 2, 1, 6, 5, 9, 9, 1], [7, 3, 1, 2, 7, 0, 0, 0, 2, 6], [9, 4, 3, 3, 7, 4, 5, 1, 0, 4], [9, 2, 8, 0, 4, 0, 8, 0, 3, 9], [6, 8, 1, 0, 1, 4, 5, 1, 7, 3], [5, 7, 2, 9, 2, 8, 6, 4, 0, 6], [5, 0, 2, 6, 9, 2, 8, 6, 5, 6], [9, 2, 6, 2, 4, 8, 6, 4, 9, 2]]
[4, 3, 4, 2, 4, 2, 6, 2, 0, 5]


### 17. Алгоритм Дейкстры на numpy

In [ ]:
# Дописать код здесь
# аналогично - непонятно