<a href="https://colab.research.google.com/github/Sinrez/pyCoursera/blob/master/stepic_array_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:

lst = [4, 5, 6]
arr = np.array(lst)
print(arr) # [4 5 6]

[4 5 6]


In [ ]:
print(arr.dtype) # int64

int64


In [ ]:
a = np.arange(3, 11, 2) # Начало, конец, шаг
print(a) # [3 5 7 9]

[3 5 7 9]


In [ ]:
a = np.array([[1, 2, 3], 
              [4, 5, 6]])

b = np.zeros_like(a)
print(b)
# Результат 
# [[0 0 0]
#  [0 0 0]]

[[0 0 0]
 [0 0 0]]


In [ ]:
a = np.random.random(size=(2, 2))
print(a)

[[0.82569728 0.04924052]
 [0.17041764 0.80503907]]


In [ ]:
a = np.random.randint(1, 20, size=(2, 4))
print(a)

[[18 16  3 18]
 [ 7 16 14 12]]


In [ ]:
arr = np.linspace(1, 2, num=5, retstep=True)
print(arr) # (array([1.  , 1.25, 1.5 , 1.75, 2.  ]), 0.25)
print(arr[0]) # array([1.  , 1.25, 1.5 , 1.75, 2.  ]) - сам массив
print(arr[1]) # 0.25 - шаг между элементами

(array([1.  , 1.25, 1.5 , 1.75, 2.  ]), 0.25)
[1.   1.25 1.5  1.75 2.  ]
0.25


In [ ]:
np.arange(3, 7)

array([3, 4, 5, 6])

In [ ]:
a = np.ones((8,5))
print(a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
import numpy as np
num = int(input())
arr_2 = np.linspace(0, 7, num=num, retstep=True)
print(arr_2[1])

7
1.1666666666666667


In [ ]:
import numpy as np

arr = np.arange(6)
arr = arr.reshape(2, 3)
print(arr)

[[0 1 2]
 [3 4 5]]


In [ ]:
import numpy as np

arr = np.array([[ 0,  1,  2],
                [ 3,  4,  5],
                [ 6,  7,  8],
                [ 9, 10, 11]])

arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
print(arr.shape[0])

4


In [ ]:
print(arr.shape[1])

3


In [ ]:
print(arr.shape)

(4, 3)


In [ ]:
import numpy as np

arr = np.array([[9, 8],
                [3, 8],
                [1, 2],
                [5, 5],
                [3, 4]])

In [ ]:
print(arr.shape[0])

5


In [ ]:
a = np.arange(0, 9)
arr = a.reshape(3, 3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
a = np.array([[1, -1, 3], 
              [2,  1, 5],
              [3, -1, 4]])

b = np.array([1,  4, 0])

print(a + b)

[[2 3 3]
 [3 5 5]
 [4 3 4]]


In [ ]:
A = np.array([[1, -1, 3], 
              [2,  1, 5],
              [3, -1, 4]])

B = np.array([[1,  4, 0], 
              [1, -1, 2],
              [2, -1, 1]])

print(A @ B)
# Результат
# [[ 6  2  1]
#  [13  2  7]
#  [10  9  2]]

print(A * B)
# Результат
# [[ 1 -4  0]
#  [ 2 -1 10]
#  [ 6  1  4]]

[[ 6  2  1]
 [13  2  7]
 [10  9  2]]
[[ 1 -4  0]
 [ 2 -1 10]
 [ 6  1  4]]


In [ ]:
import numpy as np

data = np.random.randint(1, 10, 3*4).reshape((3, -1))

print(data[:2, :2])

[[6 1]
 [6 7]]


In [1]:
import numpy as np
arr = np.array([4, 7, 3, 8, 9, 2])
i = np.array([-1, 2, 5])

print(arr[i])

[2 3 2]


In [ ]:
import numpy as np
arr_in = [int(input()) for _ in range(int(input()))]
#print(arr_in)
print(np.array(arr_in))