<a href="https://colab.research.google.com/github/Sinrez/pyCoursera/blob/master/symp_py_sci.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
>>> b = np.array( [2, 4, 6, 8] )
>>> b

array([2, 4, 6, 8])

In [4]:
 b.ndim

1

In [5]:
b.size

4

In [6]:
b.shape


(4,)

In [7]:
>>> a = np.arange(10)
>>> a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
>>> b = np.zeros((2, 4))
>>> b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
>>> k = np.ones((3, 5))
>>> k

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
>>> k = np.ones((3, 5))
>>> k

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [11]:
>>> a = np.arange(10)
>>> a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
>>> a = a.reshape(2, 5)
>>> a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [13]:
>>> a = a.reshape(5, 2)
>>> a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [14]:
a.ndim

2

In [15]:
>>> a = np.arange(10)
>>> a = a.reshape(2, 5)
>>> a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [16]:
>>> a[-1, :3]

array([5, 6, 7])

In [17]:
>>> a[1, :3]

array([5, 6, 7])

In [18]:
>>> a[:, 2:4] = 1000
>>> a

array([[   0,    1, 1000, 1000,    4],
       [   5,    6, 1000, 1000,    9]])

4x + 5y = 20

 x + 2y = 13

In [19]:
>>> import numpy as np
>>> coefficients = np.array([ [4, 5], [1, 2] ])
>>> dependents = np.array( [20, 13] )

In [20]:
coefficients

array([[4, 5],
       [1, 2]])

In [21]:
dependents

array([20, 13])

In [22]:
>>> answers = np.linalg.solve(coefficients, dependents)
>>> answers

array([-8.33333333, 10.66666667])

In [23]:
>>> product = np.dot(coefficients, answers)
>>> product

array([20., 13.])

In [24]:
 np.allclose(product, dependents)

True